version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    environment:
      VUE_APP_API_URL: 'http://backend:8000'

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
