version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    environment:
      VUE_APP_API_URL: 'http://backend:8000'

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
